### ISSUE TITLE
Laravel & Realtime Build Several Realtime Apps with Laravel

### ISSUE THREAD

**Issue by fastmarketo** [JuanDMeGon/laravel-realtime-build-several-realtime-applications#8]
I am subscribed to your course → Laravel & Real-time Build Several Realtime Apps with Laravel 
I have installed the latest Laravel as suggested by you, but I could not see login and register, and neither do they exist when I try to type their URL.

![image](https://user-images.githubusercontent.com/6827222/104507641-19106300-560d-11eb-8e5d-ee4a208e1395.png)

![image](https://user-images.githubusercontent.com/6827222/104507721-31807d80-560d-11eb-8126-1456df6762b1.png)

I have installed every UI as instructed by you. Can you please help me to troubleshoot?

**Comment by JuanDMeGon** [comment]
It looks like a misconfiguration of your host for the routing.
Be sure to configure a virtual host for it, or use artisan serve like in the course for simplicity.

Remember to publish the questions on the platform so I can reply faster.
